# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmQ0QvNL8QBQy21DAommxuN-LZ9rOe0Z
"""

import numpy as np
import joblib

# ==========================
# Sigmoid
# ==========================
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


# ==========================
# Dataset (AND / OR)
# ==========================
def get_dataset(gate="AND"):
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

    if gate == "AND":
        Y = np.array([[0], [0], [0], [1]])
    elif gate == "OR":
        Y = np.array([[0], [1], [1], [1]])
    else:
        raise ValueError("Gate must be AND or OR")

    return X, Y


# ==========================
# Hyperparameters
# ==========================
GATE = "AND"      # change to "OR" if needed
EPOCHS = 20000
ALPHA = 0.1

# ==========================
# Load data
# ==========================
X, Y = get_dataset(GATE)
n = X.shape[0]

# ==========================
# Initialization
# ==========================
np.random.seed(1)
W = np.random.randn(2, 1) * 0.1
b = 0.0

losses = []
grad_norms = []

# ==========================
# Training
# ==========================
for epoch in range(EPOCHS):

    Z = np.dot(X, W) + b
    A = sigmoid(Z)

    loss = -(1/n) * np.sum(Y*np.log(A) + (1-Y)*np.log(1-A))
    losses.append(loss)

    dW = (1/n) * np.dot(X.T, (A - Y))
    db = (1/n) * np.sum(A - Y)

    grad_norms.append(np.linalg.norm(dW))

    W -= ALPHA * dW
    b -= ALPHA * db

    if epoch % 5000 == 0:
        print(f"Epoch {epoch} | Loss = {loss:.6f}")

# ==========================
# Save model
# ==========================
model = {
    "gate": GATE,
    "W": W,
    "b": b,
    "losses": losses,
    "grad_norms": grad_norms
}

joblib.dump(model, "model.pkl")

print("\n✅ model.pkl successfully created")

# ==========================
# Final check
# ==========================
Z = np.dot(X, W) + b
A = sigmoid(Z)
pred = np.round(A)

print("\nRESULTS")
print("------------------------------")
print("x1 x2 | z | sigmoid(z) | pred")
print("------------------------------")

for i in range(len(X)):
    print(f"{X[i,0]}  {X[i,1]} | {Z[i,0]:.4f} | {A[i,0]:.4f} | {int(pred[i,0])}")